const ImageData = [
  {
    id: 1,
    name: "graduation",
    title: "Graduation",
    description: "Graduation 2023 from Santa Clara University",
    path: "graduation/justin.jpg",
    detailedImages: [
      { id: 1, path: "graduation/grad-1.jpg" },
      { id: 2, path: "graduation/grad-2.jpg" },
      { id: 3, path: "graduation/grad-3.jpg" },
      { id: 4, path: "graduation/grad-4.jpg" },
      { id: 5, path: "graduation/grad-5.jpg" },
      { id: 6, path: "graduation/grad-6.jpg" },
      { id: 7, path: "graduation/grad-7.jpg" },
      { id: 8, path: "graduation/grad-8.jpg" },
      { id: 9, path: "graduation/grad-9.jpg" },
      { id: 10, path: "graduation/grad-10.jpg" },
      { id: 11, path: "graduation/grad-11.jpg" },
      { id: 12, path: "graduation/grad-12.jpg" },
      { id: 13, path: "graduation/grad-13.jpg" },
      { id: 14, path: "graduation/grad-14.jpg" },
      { id: 15, path: "graduation/grad-15.jpg" },
    ],
  },
  {
    id: 2,
    name: "africa",
    title: "Africa",
    description: "2020 Africa Trip",
    path: "africa/portfolio-3.jpg",
    detailedImages: [
      { id: 1, path: "africa/portfolio-1.jpg" },
      { id: 2, path: "africa/portfolio-2.jpg" },
      { id: 3, path: "africa/portfolio-3.jpg" },
      { id: 4, path: "africa/portfolio-4.jpg" },
      { id: 5, path: "africa/portfolio-5.jpg" },
      { id: 6, path: "africa/portfolio-6.jpg" },
      { id: 7, path: "africa/portfolio-7.jpg" },
      { id: 8, path: "africa/portfolio-8.jpg" },
      { id: 9, path: "africa/portfolio-9.jpg" },
      { id: 10, path: "africa/portfolio-10.jpg" },
      { id: 11, path: "africa/portfolio-11.jpg" },
      { id: 12, path: "africa/portfolio-12.jpg" },
      { id: 13, path: "africa/portfolio-13.jpg" },
      { id: 14, path: "africa/portfolio-14.jpg" },
      { id: 15, path: "africa/portfolio-15.jpg" },
      { id: 16, path: "africa/portfolio-16.jpg" },
      { id: 17, path: "africa/portfolio-17.jpg" },
      { id: 18, path: "africa/portfolio-18.jpg" },
      { id: 19, path: "africa/portfolio-19.jpg" },
      { id: 20, path: "africa/portfolio-20.jpg" },
      { id: 21, path: "africa/portfolio-21.jpg" },
      { id: 22, path: "africa/portfolio-22.jpg" },
      { id: 23, path: "africa/portfolio-23.jpg" },
      { id: 24, path: "africa/portfolio-24.jpg" },
      { id: 25, path: "africa/portfolio-25.jpg" },
      { id: 26, path: "africa/portfolio-26.jpg" },
      { id: 27, path: "africa/portfolio-27.jpg" },
    ],
  },
  {
    id: 3,
    name: "collabs",
    title: "Brand Collabs",
    description: "Collaborations with Crook x Long Island",
    path: "collabs/hallie.jpg",
    detailedImages: [
      { id: 1, path: "collabs/crook-1.jpg" },
      { id: 2, path: "collabs/crook-2.jpg" },
      { id: 3, path: "collabs/crook-3.jpg" },
      { id: 4, path: "collabs/crook-4.jpg" },
      { id: 5, path: "collabs/crook-5.jpg" },
      { id: 6, path: "collabs/crook-6.jpg" },
      { id: 7, path: "collabs/crook-7.jpg" },
      { id: 8, path: "collabs/crook-8.jpg" },
      { id: 9, path: "collabs/crook-9.jpg" },
      { id: 10, path: "collabs/crook-10.jpg" },
      { id: 11, path: "collabs/crook-11.jpg" },
      { id: 12, path: "collabs/crook-12.jpg" },
      { id: 13, path: "collabs/crook-13.jpg" },
      { id: 14, path: "collabs/crook-14.jpg" },
      { id: 15, path: "collabs/crook-15.jpg" },
      { id: 16, path: "collabs/crook-16.jpg" },
      { id: 17, path: "collabs/crook-17.jpg" },
      { id: 18, path: "collabs/crook-18.jpg" },
      { id: 19, path: "collabs/crook-19.jpg" },
      { id: 20, path: "collabs/crook-20.jpg" },
      { id: 21, path: "collabs/crook-21.jpg" },
      { id: 22, path: "collabs/crook-22.jpg" },
      { id: 23, path: "collabs/crook-23.jpg" },
      { id: 24, path: "collabs/crook-24.jpg" },
      { id: 25, path: "collabs/crook-25.jpg" },
      { id: 26, path: "collabs/crook-26.jpg" },
      { id: 27, path: "collabs/crook-27.jpg" },
      { id: 28, path: "collabs/crook-28.jpg" },
      { id: 29, path: "collabs/crook-29.jpg" },
      { id: 30, path: "collabs/crook-30.jpg" },
      { id: 31, path: "collabs/crook-31.jpg" },
      { id: 32, path: "collabs/crook-32.jpg" },
      { id: 33, path: "collabs/crook-33.jpg" },
      { id: 34, path: "collabs/crook-34.jpg" },
      { id: 35, path: "collabs/crook-35.jpg" },
      { id: 36, path: "collabs/crook-36.jpg" },
      { id: 37, path: "collabs/crook-37.jpg" },
      { id: 38, path: "collabs/crook-38.jpg" },
      { id: 39, path: "collabs/crook-39.jpg" },
    ],
  },
];

export { ImageData };
