const SECTIONIMAGES = [
  {
    id: 1,
    name: "graduation",
    title: "Graduation",
    description: "Graduation 2023 from Santa Clara University",
    path: "justin.jpg",
    detailedImages: [
      { id: 1, path: "portfolio-15.jpg" },
      { id: 2, path: "portfolio-16.jpg" },
      { id: 3, path: "portfolio-17.jpg" },
      { id: 4, path: "portfolio-18.jpg" },
      { id: 5, path: "portfolio-19.jpg" },
    ],
  },
  {
    id: 2,
    name: "africa",
    title: "Africa",
    description: "2020 Africa Trip",
    path: "portfolio-3.jpg",
    detailedImages: [
      { id: 1, path: "africa/portfolio-1.jpg" },
      { id: 2, path: "africa/portfolio-2.jpg" },
      { id: 3, path: "africa/portfolio-3.jpg" },
      { id: 4, path: "africa/portfolio-4.jpg" },
      { id: 5, path: "africa/portfolio-5.jpg" },
      { id: 6, path: "africa/portfolio-6.jpg" },
      { id: 7, path: "africa/portfolio-7.jpg" },
      { id: 8, path: "africa/portfolio-8.jpg" },
      { id: 9, path: "africa/portfolio-9.jpg" },
      { id: 10, path: "africa/portfolio-10.jpg" },
      { id: 11, path: "africa/portfolio-11.jpg" },
      { id: 12, path: "africa/portfolio-12.jpg" },
      { id: 13, path: "africa/portfolio-13.jpg" },
      { id: 14, path: "africa/portfolio-14.jpg" },
      { id: 15, path: "africa/portfolio-15.jpg" },
      { id: 16, path: "africa/portfolio-16.jpg" },
      { id: 17, path: "africa/portfolio-17.jpg" },
      { id: 18, path: "africa/portfolio-18.jpg" },
      { id: 19, path: "africa/portfolio-19.jpg" },
      { id: 20, path: "africa/portfolio-20.jpg" },
      { id: 21, path: "africa/portfolio-21.jpg" },
      { id: 22, path: "africa/portfolio-22.jpg" },
      { id: 23, path: "africa/portfolio-23.jpg" },
      { id: 24, path: "africa/portfolio-24.jpg" },
      { id: 25, path: "africa/portfolio-25.jpg" },
      { id: 26, path: "africa/portfolio-26.jpg" },
      { id: 27, path: "africa/portfolio-27.jpg" },
    ],
  },
  {
    id: 3,
    name: "collabs",
    title: "Brand Collabs",
    description: "Collaborations with Crook x Long Island",
    path: "hallie.jpg",
    detailedImages: [
      { id: 1, path: "collabs/hallie.jpg" },
      { id: 2, path: "collabs/hallie.jpg" },
      { id: 3, path: "collabs/hallie.jpg" },
      { id: 4, path: "collabs/hallie.jpg" },
      { id: 5, path: "collabs/hallie.jpg" },
    ],
  },
];

export default SECTIONIMAGES;
